### ISSUE TITLE
Add Forum model and routes

### ISSUE THREAD

**Issue by vixrant** [djunicode/masters-information-portal#1]
Schema would be this for now (subject to change in the future)

- question
  - titile: String
  - text: String
  - poster: ObjectId>User
  - createdAt: Date
  - updatedAt: Date
  - upvoters: [ObjectId>User]
  - downvotes: [ObjectId>User]
- answers: [Array of the following schema]
  - text: String
  - poster: ObjectId>User
  - createdAt: Date
  - updatedAt: Date
  - upvoters: [ObjectId>User]
  - downvotes: [ObjectId>User]
  - pinned: Boolean (default: false)

**Comment by namandangi** [comment]
I'll be working on this issue.

**Comment by vixrant** [comment]
Update, a better schema would be having more top level attributes

Schema would be this for now (subject to change in the future)

- titile: String
- text: String
- poster: ObjectId>User
- createdAt: Date
- updatedAt: Date
- upvoters: [ObjectId>User]
- downvotes: [ObjectId>User]
- answers: [Array of the following schema]
  - text: String
  - poster: ObjectId>User
  - createdAt: Date
  - updatedAt: Date
  - upvoters: [ObjectId>User]
  - downvotes: [ObjectId>User]
  - pinned: Boolean (default: false)
