### ISSUE TITLE
Add supporting libraries

### ISSUE THREAD

**Issue by vixrant** [djunicode/masters-information-portal#22]
For now add the following:

- Winston for logging, we need a good logging framework and pipeline. All logs should go on terminal as well as a file.
- Dotenv for environment variables. Make two dotenv files: `.env` and `.env.development` for when `NODE_ENV=development`.
- A pipeline for deploying using one command. Basically, a script file `build.sh` which would build react, and start the backend server.
- Add COR to express, only allow localhost:3000 for react.

**Comment by jaypajji4444** [comment]
I will work on this issue..
