### ISSUE TITLE
Add Tag model and routes

### ISSUE THREAD

**Issue by vixrant** [djunicode/masters-information-portal#3]
Instead of having random strings as "tags" we can have tags which are monitored. So if there's a University or a Domain that becomes a tag for a question or a user. This would make managing the website much more easier with a single model, plus you have good support for autocomplete if you have a fixed database of tags.

Schema would be this for now (subject to change in the future)

- name: String
- isSchool: Boolean (default: false)

**Comment by YJDoc2** [comment]
I'll do this

**Comment by jaypajji4444** [comment]
I and Yashodhan will work on this issue

**Comment by YJDoc2** [comment]
I have added an 'alt' field so we can store all variations of the tag under same heading, like AI, A.I. and ai under Artificial Intelligence
