### ISSUE TITLE
Searching forum posts and filter by tag slugs

### ISSUE THREAD

**Issue by vixrant** [djunicode/masters-information-portal#32]
- We should be able to fuzz search through an endpoint.
See: https://fusejs.io or any other library which may be better.

It should fuzzy search through all of post's question attributes, and tags. Answers you can skip.

- Add Tags to Forum model. Forum post can have an array of Tags as objectID refs.

- Add special handling of filtering by tags in GET / of posts. Discuss this with us before implementing.

**Comment by namandangi** [comment]
I'll work on this

**Comment by jaypajji4444** [comment]
I am working on this issue..
