### ISSUE TITLE
Problems with Chat controller

### ISSUE THREAD

**Issue by vixrant** [djunicode/masters-information-portal#33]
- Add a route to get all chats of a user.
- User should have access only to his own chats.

**Comment by vixrant** [comment]
Socket.io:

- Use verifyJwt function from infra to check if Jwt token is valid
- In "open chat", check if user has access to the chat ID sent. If yes, then only join him in the room. Otherwise send a 403 message using Socket.io.

**Comment by heth0218** [comment]
I shall solve this issue
