### ISSUE TITLE
Add User model and authentication support

### ISSUE THREAD

**Issue by vixrant** [djunicode/masters-information-portal#4]
You'll have to add support as well. This includes the "auth required" middleware which will be used by others.

Schema would be this for now (subject to change in the future)

- email: String
- password: String
- biography: String
- graduationYear: Number
- socialLinks: [Array of the following schema]
- currentSchool: [ObjectId>Tag]
- accepts: [ObjectId>Tag]
- rejects: [ObjectId>Tag]
- pinnedQuestions: [ObjectId>Forum]

**Comment by yash-chad** [comment]
I'll like to work on this
