### ISSUE TITLE
Add roles to user model

### ISSUE THREAD

**Issue by siddinc** [djunicode/masters-information-portal#54]
- Add roles for user: 'Admin' (if roles array is empty, it means he/she is a normal user)
- Add user role authorization middleware to be used in routes
- middleware should be of the format eg:
hasRoles(listRoles) {
    return function(req, res, next) {...};
} 
- add this middleware in routes for eg:
routes.get('/', loginRequired, hasRoles(['Admin']))
- Also add roles as a key in JWT having value as an array of roles for that particular user

**Comment by heth0218** [comment]
I solve this issue !

**Comment by heth0218** [comment]
I shall solve this issue!

**Comment by siddinc** [comment]
Pls add necessary documentation for existing code and also modify variable names according to the standards given to you in the beginning.
