### ISSUE TITLE
Revamp Forum model for answers referencing

### ISSUE THREAD

**Issue by siddinc** [djunicode/masters-information-portal#57]
- Remove answers from the forum schema and add two fields: isAnswer (Boolean) and parentId(object_id)
- This logic treats a question and answer as being objects from the same schema. The only difference between a question and answer are isAnswer which will be true for and answer and false otherwise.
- if isAnswer == true then set parentId as questions object_id
else if isAnswer == false then set parentId as null
- Make a mongoose pre-hook implementing the aforementioned logic (throw validation_error if not question/answer object is in an invalid format)

**Comment by YJDoc2** [comment]
I'm working on this
