### ISSUE TITLE
Add and serve apiDoc documentation (for Tags)

### ISSUE THREAD

**Issue by vixrant** [djunicode/masters-information-portal#70]
[Github: apiDoc](https://github.com/apidoc/apidoc)

- Add a `package.json` script `docs` which will generate the documentation into a folder, `docs/`
- Serve the docs in express at route `/api/docs`
- Document Tag route first, then we can decide how to document the whole project.

Documentation can include the following annotations:

- `@api` for method, route, and 1 line description
- `@apiName` for naming a route (GetTagList, GetTagBySlug)
- `@apiDescription`, if required, for special routes or special notes.
- `@apiGroup` for each resource (Tag)
- `@apiParam` for the fields which can be passed in body or filter.
- `@apiPermission`, first use `@apiDefine` in auth middleware to define the user permission model, then use that in authRequired routes.
- `@apiSuccess`to define the fields in response document.

Avoid `@apiError` and `@apiHeader` for now.

**Comment by YJDoc2** [comment]
Api Doc generates a handlebars template which is supposed to be dynamically filled in at client side by script tag functions, but they are blocked by CSP policies of browsers.That's why we cannot directly serve the Docs generated by apidoc.Should we try to change to another doc generating library?

**Comment by vixrant** [comment]
apidoc generates HTML/CSS/JS tho, not handlebars

**Comment by YJDoc2** [comment]
The issue was with helmet middleware CSP used,fixed it.

**Comment by YJDoc2** [comment]
Complete Page 

![Screenshot_2020-03-30 Docmentation of routes](https://user-images.githubusercontent.com/54112038/77897150-e8865500-7296-11ea-8b88-c2676b81925f.png)

NOTE : The side-bar, in actual page is sticky, and stays always on side for all time

Page as visible in window :
![Screenshot_2020-03-30 Docmentation of routes(1)](https://user-images.githubusercontent.com/54112038/77897382-37cc8580-7297-11ea-8d6f-82f4fa07f061.png)

**Comment by YJDoc2** [comment]
Also added jsDoc documentation for documenting backend code(currently Tags only).

Documentation :
![Screenshot_2020-03-30 JSDoc Namespace TagSchema](https://user-images.githubusercontent.com/54112038/77900677-04402a00-729c-11ea-962d-c8ff93fa3206.png)

It can also show the files being documented : 
![Screenshot_2020-03-30 JSDoc Source tag js](https://user-images.githubusercontent.com/54112038/77900788-305bab00-729c-11ea-8356-904896ec46b6.png)
