### ISSUE TITLE
Add Notifications support

### ISSUE THREAD

**Issue by vixrant** [djunicode/masters-information-portal#95]
Notifications should be easy to implement in existing routes, and they should work with Forum and chat both.

https://docs.google.com/document/d/1SSU6l7l6tRl1G0PQrd_ixpj-1Sb4IBGMRCayBg-Jw60/edit?usp=sharing

**Comment by vixrant** [comment]
@jaypajji4444 comment kar de

**Comment by jaypajji4444** [comment]
👍.. Will work accordingly to doc...
